"""Self-contained freqtrade IStrategy template generated by regime_framework.

The strategy reads a feather file at startup with stitched OOS predictions
([date, label, close]) and merges them onto freqtrade's OHLCV frame using
merge_asof(direction="backward") — same anti-lookahead pattern used by the
framework itself in data/alignment.py.

Label semantics:
  - "bull"  -> enter long  (and exit short if held)
  - "bear"  -> enter short (only if can_short=True; spot strategies skip it)
  - ""      -> flat (no entry, exits open positions on the next flip)

We rely on string.Template (stdlib) instead of Jinja2: zero runtime dep, and
the `${var}` substitution is safer than f-strings inside a Python file body
that itself contains many braces.
"""
from __future__ import annotations

from pathlib import Path
from string import Template


STRATEGY_TEMPLATE = Template(r'''"""Auto-generated by regime_framework. Do not edit; regenerate via `regime-run backtest`.

Predictor: ${PREDICTOR_NAME}
Target:    ${TARGET}/${QUOTE}${SETTLE_TAG}  (${MARKET_TYPE}, ${TIMEFRAME})
Source:    ${PREDICTIONS_PATH}
"""
from pathlib import Path

import pandas as pd

from freqtrade.strategy import IStrategy


class ${CLASS_NAME}(IStrategy):
    """Regime-following strategy: long on 'bull', short on 'bear', flat otherwise."""

    INTERFACE_VERSION = 3
    timeframe = "${TIMEFRAME}"
    can_short = ${CAN_SHORT}

    # The model dictates positions; freqtrade's stoploss/ROI must be
    # generously slack so we exit only on regime flip via populate_exit_trend.
    stoploss = -0.99
    minimal_roi = {"0": 100}
    process_only_new_candles = True
    use_exit_signal = True
    startup_candle_count = 0

    # CRITICAL: market orders, not limit. Default freqtrade order_types use
    # `limit` which in backtest only fills if the next bar's range crosses
    # the signal price. In trending markets (e.g. BTC down-trend with bear
    # signals), the limit price sits on the wrong side of the orderbook so
    # the order never fills -> trade silently dropped. Market = guaranteed
    # fill at next bar's open, which is the only realistic execution model
    # given the backtest only has OHLCV (no real orderbook).
    order_types = {
        "entry": "market",
        "exit": "market",
        "stoploss": "market",
        "stoploss_on_exchange": False,
    }

    _PRED_PATH = Path(r"${PREDICTIONS_PATH}")
    _preds_cache = None

    def _load_preds(self):
        if ${CLASS_NAME}._preds_cache is None:
            df = pd.read_feather(${CLASS_NAME}._PRED_PATH)
            # Keep tz-aware UTC; precision is aligned dynamically at merge
            # time to whatever freqtrade hands us (ms / us / ns).
            df["date"] = pd.to_datetime(df["date"], utc=True)
            ${CLASS_NAME}._preds_cache = (
                df[["date", "label"]].sort_values("date").reset_index(drop=True)
            )
        return ${CLASS_NAME}._preds_cache

    def populate_indicators(self, dataframe, metadata):
        preds = self._load_preds().copy()
        dataframe = dataframe.copy()
        dataframe["date"] = pd.to_datetime(dataframe["date"], utc=True)
        # Align preds' datetime precision to freqtrade's OHLCV precision
        # dynamically. pandas.merge_asof refuses joins across different
        # datetime64 precisions (ms vs us vs ns), even when the wall-clock
        # matches. We read whatever freqtrade gives us and follow it —
        # so this strategy survives future pandas/freqtrade precision shifts.
        preds["date"] = preds["date"].astype(dataframe["date"].dtype)
        # Backward merge_asof: at bar t, use the most recent label whose
        # timestamp <= t. Tolerance = 1 bar so we never carry a stale label
        # across data gaps.
        merged = pd.merge_asof(
            dataframe.sort_values("date"),
            preds,
            on="date",
            direction="backward",
            tolerance=pd.Timedelta("${TIMEFRAME}"),
        )
        dataframe["regime_label"] = merged["label"].fillna("").astype(str).values
        return dataframe

    def populate_entry_trend(self, dataframe, metadata):
        dataframe["enter_long"] = (dataframe["regime_label"] == "bull").astype(int)
        if self.can_short:
            dataframe["enter_short"] = (dataframe["regime_label"] == "bear").astype(int)
        return dataframe

    def populate_exit_trend(self, dataframe, metadata):
        # Exit longs the moment the label is no longer "bull";
        # exit shorts the moment the label is no longer "bear".
        dataframe["exit_long"] = (dataframe["regime_label"] != "bull").astype(int)
        if self.can_short:
            dataframe["exit_short"] = (dataframe["regime_label"] != "bear").astype(int)
        return dataframe
''')


def render_strategy(
    *,
    class_name: str,
    timeframe: str,
    can_short: bool,
    predictions_path: Path,
    predictor_name: str,
    target: str,
    quote: str,
    settle: str,
    market_type: str,
) -> str:
    """Substitute placeholders into STRATEGY_TEMPLATE and return the file body."""
    settle_tag = f":{settle}" if market_type == "futures" else ""
    return STRATEGY_TEMPLATE.substitute(
        CLASS_NAME=class_name,
        TIMEFRAME=timeframe,
        CAN_SHORT="True" if can_short else "False",
        PREDICTIONS_PATH=str(Path(predictions_path).resolve()),
        PREDICTOR_NAME=predictor_name,
        TARGET=target,
        QUOTE=quote,
        SETTLE_TAG=settle_tag,
        MARKET_TYPE=market_type,
    )


def write_strategy_file(
    *,
    out_dir: Path,
    class_name: str,
    timeframe: str,
    can_short: bool,
    predictions_path: Path,
    predictor_name: str,
    target: str,
    quote: str,
    settle: str,
    market_type: str,
) -> Path:
    """Render the strategy and write it as `<out_dir>/<class_name>.py`. Return the path."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    body = render_strategy(
        class_name=class_name,
        timeframe=timeframe,
        can_short=can_short,
        predictions_path=predictions_path,
        predictor_name=predictor_name,
        target=target,
        quote=quote,
        settle=settle,
        market_type=market_type,
    )
    out_path = out_dir / f"{class_name}.py"
    out_path.write_text(body)
    return out_path
